import RuntimeSafetyKernels.Contracts
import RuntimeSafetyKernels.Shape

namespace RuntimeSafetyKernels.Shape.Extract

open RuntimeSafetyKernels.Shape

structure CTensorShape where
  dimensions : Array UInt32
  deriving Repr

def toShape (shape : CTensorShape) : Shape :=
  shape.dimensions.toList.map UInt32.toNat

def validateExtractedShape (shape : CTensorShape) : Bool :=
  validateShapeAtCompileTime (toShape shape)

def generateCHeader : String :=
  "#ifndef RSK_SHAPE_H\n#define RSK_SHAPE_H\n// Canonical contract generated by Lean extraction.\n#endif\n"

def main : IO Unit := do
  IO.FS.createDirAll "src/extracted"
  IO.FS.writeFile "src/extracted/rsk_shape.h" generateCHeader
  let ok := validateExtractedShape ⟨#[2, 3, 4]⟩
  IO.println s!"shape extraction smoke test: {ok}"

end RuntimeSafetyKernels.Shape.Extract
