import RuntimeSafetyKernels.Contracts
import RuntimeSafetyKernels.Policy

namespace RuntimeSafetyKernels.Policy.Extract

open RuntimeSafetyKernels.Policy

structure CPolicyConfig where
  maxTokens : UInt32
  policyVersion : String
  deriving Repr

structure CDecodeResult where
  allowed : Bool
  token : String
  error : String
  deriving Repr

structure CPolicyManager where
  manager : PolicyManager

def fromCPolicyConfig (cfg : CPolicyConfig) : PolicyConfig :=
  {
    maxTokens := cfg.maxTokens.toNat
    policyVersion := cfg.policyVersion
  }

def newCPolicyManager (cfg : CPolicyConfig) : CPolicyManager :=
  let manager := initDefaultPolicyManager (fromCPolicyConfig cfg)
  ⟨manager⟩

def cDecode (m : CPolicyManager) (token : String) : IO (CDecodeResult × CPolicyManager) := do
  let result := decodeToken m.manager token
  match result with
  | Except.ok accepted =>
      return (⟨true, accepted, ""⟩, m)
  | Except.error err =>
      return (⟨false, "", err⟩, m)

def generateCHeader : String :=
  "#ifndef RSK_POLICY_H\n#define RSK_POLICY_H\n// Canonical contract generated by Lean extraction.\n#endif\n"

def main : IO Unit := do
  IO.FS.createDirAll "src/extracted"
  IO.FS.writeFile "src/extracted/rsk_policy.h" generateCHeader
  let cfg : CPolicyConfig := ⟨1024, "1.0"⟩
  let manager := newCPolicyManager cfg
  let (result, _) ← cDecode manager "safe_token"
  IO.println s!"policy extraction smoke test: {reprStr result}"

end RuntimeSafetyKernels.Policy.Extract
